// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "github.com/bhuvi1021/TripleA/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// ITransactionRepository is an autogenerated mock type for the ITransactionRepository type
type ITransactionRepository struct {
	mock.Mock
}

type ITransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ITransactionRepository) EXPECT() *ITransactionRepository_Expecter {
	return &ITransactionRepository_Expecter{mock: &_m.Mock}
}

// CreateTransaction provides a mock function with given fields: req
func (_m *ITransactionRepository) CreateTransaction(req models.CreateTransactionArgs) (models.CreateTransactionResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 models.CreateTransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(models.CreateTransactionArgs) (models.CreateTransactionResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(models.CreateTransactionArgs) models.CreateTransactionResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(models.CreateTransactionResponse)
	}

	if rf, ok := ret.Get(1).(func(models.CreateTransactionArgs) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ITransactionRepository_CreateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransaction'
type ITransactionRepository_CreateTransaction_Call struct {
	*mock.Call
}

// CreateTransaction is a helper method to define mock.On call
//   - req models.CreateTransactionArgs
func (_e *ITransactionRepository_Expecter) CreateTransaction(req interface{}) *ITransactionRepository_CreateTransaction_Call {
	return &ITransactionRepository_CreateTransaction_Call{Call: _e.mock.On("CreateTransaction", req)}
}

func (_c *ITransactionRepository_CreateTransaction_Call) Run(run func(req models.CreateTransactionArgs)) *ITransactionRepository_CreateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.CreateTransactionArgs))
	})
	return _c
}

func (_c *ITransactionRepository_CreateTransaction_Call) Return(_a0 models.CreateTransactionResponse, _a1 error) *ITransactionRepository_CreateTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ITransactionRepository_CreateTransaction_Call) RunAndReturn(run func(models.CreateTransactionArgs) (models.CreateTransactionResponse, error)) *ITransactionRepository_CreateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewITransactionRepository creates a new instance of ITransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITransactionRepository {
	mock := &ITransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
